const HEADERS = { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' };
const REPO = 'leowizard88/mcsp';
const MAX_FILE = 12000000;
const json = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: HEADERS });
const clean = value => String(value || '').replace(/[\u0000-\u001f\u007f]/g, ' ').replace(/\s+/g, ' ').trim();
const bearer = request => { const auth = request.headers.get('authorization') || ''; return auth.toLowerCase().startsWith('bearer ') ? auth.slice(7).trim() : request.headers.get('x-mancuspie-token') || ''; };
const slugify = value => clean(value).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 70) || 'materiale';
const yaml = value => String(value || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r?\n/g, ' ');
const base64Clean = value => String(value || '').replace(/^data:[^;]+;base64,/, '').replace(/\s/g, '');
const toBase64 = value => btoa(unescape(encodeURIComponent(value)));
const repoName = env => env.GITHUB_REPO || REPO;
const contentUrl = (env, path) => 'https://api.github.com/repos/' + repoName(env) + '/contents/' + encodeURIComponent(path).replace(/%2F/g, '/');
const githubHeaders = env => ({ authorization: 'Bearer ' + env.GITHUB_TOKEN, accept: 'application/vnd.github+json', 'user-agent': 'mancuspie-materials' });
async function getUser(env, request) { const token = bearer(request); if (!env.CHAT_MESSAGES || !token) return null; const session = await env.CHAT_MESSAGES.get('auth:session:' + token, 'json').catch(() => null); return session?.userId ? await env.CHAT_MESSAGES.get('auth:user:' + session.userId, 'json').catch(() => null) : null; }
async function githubPut(env, path, content, message) { if (!env.GITHUB_TOKEN) return { ok:false, status:500, error:'GITHUB_TOKEN mancante nei segreti Cloudflare' }; const response = await fetch(contentUrl(env,path), { method:'PUT', headers:githubHeaders(env), body:JSON.stringify({ message, content }) }); const data=await response.json().catch(()=>({})); return response.ok ? {ok:true,data} : {ok:false,status:response.status,error:data.message||'Errore GitHub'}; }
function materialFile(user, data, date) { return ['---','title: "'+yaml(data.title)+'"','author: "'+yaml(user.username)+'"','resource_name: "'+yaml(data.name)+'"','resource_kind: "'+data.kind+'"','resource_url: "'+yaml(data.url)+'"','resource_format: "'+data.format+'"','tipo: "'+data.tipo+'"',data.category ? 'category: "'+yaml(data.category)+'"' : '',data.description ? 'description: "'+yaml(data.description)+'"' : '','date: "'+date+'"','tags: materiali','---'].filter(Boolean).join('\n')+'\n'; }
function validateLink(value) { try { const url=new URL(clean(value)); return /^https?:$/.test(url.protocol) ? url.href : ''; } catch { return ''; } }
export async function onRequestPost({request,env}) { const user=await getUser(env,request); if (!user || user.role !== 'redattore') return json({error:'Permesso redattore richiesto'},403); let data; try { data=await request.json(); } catch { return json({error:'JSON non valido'},400); } const title=clean(data.title).slice(0,160),name=clean(data.name).slice(0,120),description=clean(data.description).slice(0,1200),category=clean(data.category).slice(0,80),tipo=clean(data.tipo).toLowerCase(),kind=clean(data.kind).toLowerCase(); if(!title)return json({error:'Titolo richiesto'},400); if(!['file','link'].includes(kind))return json({error:'Tipo di materiale non valido'},400);if(!['libro','sito','video','altro'].includes(tipo))return json({error:'Tipo archivio non valido'},400); const stamp=new Date().toISOString(),id=stamp.replace(/[-:.TZ]/g,'').slice(0,14)+'-'+slugify(title); let url='',format='other'; if(kind==='link'){url=validateLink(data.url);if(!url)return json({error:'Inserisci un link http o https valido'},400)}else{const filename=clean(data.filename).replace(/[^a-zA-Z0-9._-]/g,'-').slice(0,100),raw=base64Clean(data.content),extension=(filename.split('.').pop()||'').toLowerCase();if(!filename||!raw)return json({error:'File mancante'},400);if(raw.length>MAX_FILE)return json({error:'File troppo pesante (massimo circa 9 MB)'},413);if(!extension||['html','htm','js','mjs','svg','css','php'].includes(extension))return json({error:'Formato file non supportato'},400);format=extension==='pdf'?'pdf':extension==='epub'?'epub':'other';const path='src/assets/materiali/'+id+'-'+filename;const upload=await githubPut(env,path,raw,'upload material '+filename);if(!upload.ok)return json({error:upload.error},upload.status||500);url='/assets/materiali/'+id+'-'+filename;} const record=await githubPut(env,'src/content/materiali/'+id+'.md',toBase64(materialFile(user,{title,name,description,category,tipo,kind,url,format},stamp)),'add material '+id);if(!record.ok)return json({error:record.error},record.status||500);return json({ok:true,url:'/materiali/'},201); }
